"use client";

import Link from "next/link";
import { ArrowRight, CheckCircle2, CircleHelp, FolderKanban, ListChecks, Plus, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useDemo } from "./demo-provider";
import { CategoryIcon, PageHeading, Panel, StatusBadge } from "./primitives";

export function DemoDashboard() {
  const { account, problems, basePath } = useDemo();
  const query = basePath ? "" : "?demo=1";
  const openTasks = problems.flatMap((problem) => problem.tasks.filter((task) => !task.done));
  const attention = problems.filter((problem) => problem.status === "Needs your input");
  return <div className="space-y-8">
    <PageHeading eyebrow="Your overview" title={account.displayName ? `Welcome, ${account.displayName}` : "Welcome to Avenli"} description="A little clarity on what matters, what’s moving, and what needs you next." actionHref={`${basePath}/problems/new${query}`} />
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[{ label: "Problems", value: problems.length, icon: FolderKanban }, { label: "Need your input", value: attention.length, icon: CircleHelp }, { label: "Open demo tasks", value: openTasks.length, icon: ListChecks }, { label: "Ready to review", value: problems.filter((problem)=>problem.status==="Ready to review").length, icon: CheckCircle2 }].map(({ label, value, icon: Icon }) => <div key={label} className="avenli-panel flex items-center justify-between rounded-[1.15rem] p-4"><div><p className="text-xs font-medium text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-semibold tracking-[-.04em] text-[#111653]">{value}</p></div><span className="flex size-9 items-center justify-center rounded-xl bg-[#eff0ff] text-primary"><Icon className="size-[18px]" aria-hidden="true" /></span></div>)}</div>
    {attention[0] && <section className="flex flex-wrap items-center justify-between gap-5 rounded-xl border border-amber-200 bg-amber-50/60 p-5 sm:p-6"><div className="max-w-xl"><p className="text-xs font-semibold uppercase tracking-wider text-amber-900">Needs your attention · sample</p><h2 className="mt-2 text-lg font-semibold">{attention[0].unknowns[0]?.question}</h2><p className="mt-1 text-sm text-muted-foreground">{attention[0].title} · {attention[0].unknowns[0]?.detail}</p></div><Button asChild variant="outline"><Link href={`${basePath}/problems/${attention[0].id}`}>Review problem<ArrowRight aria-hidden="true" /></Link></Button></section>}
    <div className="grid items-stretch gap-5 xl:grid-cols-[minmax(0,1.55fr)_minmax(280px,.75fr)]"><section aria-labelledby="active-title" className="avenli-panel overflow-hidden rounded-[1.25rem]"><div className="flex items-center justify-between border-b px-5 py-4 sm:px-6"><div><h2 id="active-title" className="font-semibold tracking-[-.02em] text-[#111653]">Recent problems</h2><p className="mt-1 text-xs text-muted-foreground">Explore a complete fictional workspace.</p></div><Link href={`${basePath}/problems${query}`} className="text-sm font-semibold text-primary hover:underline">View all</Link></div><div className="divide-y">{problems.map((problem)=><Link key={problem.id} href={`${basePath}/problems/${problem.id}`} className="group flex items-center gap-4 px-5 py-4 transition hover:bg-[#f8f9ff] sm:px-6"><CategoryIcon category={problem.category}/><div className="min-w-0 flex-1"><h3 className="truncate text-sm font-semibold text-[#151955] group-hover:text-primary">{problem.title}</h3><p className="mt-1 truncate text-xs text-muted-foreground">{problem.goal}</p></div><span className="hidden sm:inline-flex"><StatusBadge status={problem.status}/></span><ArrowRight className="size-4 shrink-0 text-muted-foreground transition group-hover:translate-x-0.5 group-hover:text-primary" aria-hidden="true"/></Link>)}</div></section><aside className="avenli-glow relative flex min-h-72 flex-col overflow-hidden rounded-[1.25rem] border border-[#d9def6] p-6"><div className="absolute -right-16 -top-16 size-52 rounded-full bg-violet-300/25 blur-3xl" aria-hidden="true"/><div className="relative"><span className="flex size-11 items-center justify-center rounded-2xl bg-white/80 text-primary shadow-sm"><Sparkles className="size-5" aria-hidden="true"/></span><p className="mt-6 text-xs font-semibold uppercase tracking-[.16em] text-[#5d5da5]">Keep going</p><h2 className="mt-2 max-w-xs text-2xl font-semibold leading-tight tracking-[-.04em] text-[#111653]">Turn complex problems into clear next steps.</h2><p className="mt-3 text-sm leading-relaxed text-muted-foreground">Create a temporary draft or inspect a full fictional scenario.</p></div><div className="relative mt-auto pt-6"><Button asChild><Link href={`${basePath}/problems/new${query}`}><Plus aria-hidden="true"/>New problem</Link></Button></div></aside></div>
    <div className="grid gap-5 xl:grid-cols-2"><Panel title="A clear next step" description="Tasks from the sample scenarios."><ul className="divide-y">{problems.flatMap((problem) => problem.tasks.filter((task) => !task.done).slice(0, 1).map((task) => <li key={task.id}><Link href={`${basePath}/problems/${problem.id}?view=tasks`} className="flex items-start justify-between gap-4 py-3 hover:text-primary"><div><p className="text-sm font-medium">{task.title}</p><p className="mt-1 text-xs text-muted-foreground">{problem.title}</p></div><ArrowRight className="mt-1 size-4 shrink-0" aria-hidden="true" /></Link></li>))}</ul></Panel><Panel title="How to explore" description="Try the workspace without running an agent."><ol className="space-y-4 text-sm leading-relaxed"><li><span className="mr-3 text-primary">01</span>Open a scenario and inspect its goal, plan, and open questions.</li><li><span className="mr-3 text-primary">02</span>Compare options and follow the sample decision trail.</li><li><span className="mr-3 text-primary">03</span>Check off a demo task or create a draft of your own.</li></ol></Panel></div>
  </div>;
}
