"use client";
import { useRef, useState } from "react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Panel, EmptyState } from "@/components/demo/primitives";
import { detailSchema, jobActive, jobLabel, type ProblemDetail } from "@/lib/workspace/contracts";
import { post, useRemote } from "./remote";
import { EvidenceQuality } from "./evidence-quality";
import { HumanInput } from "./human-input";
import { MonitoringConditions } from "./monitoring-conditions";
import { CalendarActions } from "./calendar-actions";
import { TaskList } from "./task-list";
import { ProblemResolution } from "./problem-resolution";
import { FollowUpAnalysis } from "./follow-up-analysis";
import { cn } from "@/lib/utils";
const active = (value: ProblemDetail) => value.problem.status !== "solved" && (jobActive(value.job) || value.conditions.some((condition) => condition.status === "checking"));
const sections = ["Overview", "Plan", "Research", "Options", "Risks", "Tasks", "Decisions"];
const labels: Record<string, string> = { ACTION_REQUIRED: "Waiting for your answers", RESUME: "Updating the plan with your answers", PENDING: "Queued", INTAKE: "Understanding your problem", PLAN: "Building a plan", RESEARCH: "Researching priority questions", VERIFY: "Checking evidence", OPTIONS: "Comparing approaches", CRITIQUE: "Challenging the plan", DECIDE: "Preparing a recommendation", TASKS: "Drafting tasks", COMPLETED: "Analysis complete", FAILED: "Analysis stopped", CANCELLED: "Analysis stopped" };
function TextList({ items }: { items: string[] }) { return items.length ? <ul className="space-y-2 text-sm leading-relaxed">{items.map((text, index) => <li className="break-words" key={index}>• {text}</li>)}</ul> : <p className="text-sm text-muted-foreground">None recorded.</p>; }
const Missing = () => <EmptyState title="No saved result for this stage yet" detail="Results appear here when the stage finishes successfully." />;

export function LiveProblem({ id }: { id: string }) {
  const { data, error, refresh } = useRemote(`/api/problems/${id}`, detailSchema, active);
  const search = useSearchParams(); const raw = search.get("view") ?? "overview"; const view = sections.some((section) => section.toLowerCase() === raw) ? raw : "overview";
  const [retryError, setRetryError] = useState(""); const [retrying, setRetrying] = useState(false); const retryId = useRef<string | null>(null); const lock = useRef(false);
  if (!data) return <div className="space-y-4"><p role={error ? "alert" : "status"}>{error || "Loading your saved problem…"}</p><Button variant="outline" onClick={refresh}>Refresh status</Button><Link className="ml-4 text-primary underline" href="/problems">All problems</Link></div>;
  const s = data.snapshot; const running = jobActive(data.job); const solved = data.problem.status === "solved"; const status = solved ? "Solved" : jobLabel(data.job);
  const investigated=s?.research?.questions ?? (s?.research ? [s.research.question] : []); const plannedResearch=new Set(s?.plan?.steps.flatMap((step)=>step.researchQuestions)??[]).size;
  const progress = s ? Math.round([s.intake, s.plan, s.research, s.verification, s.options, s.critique, s.decision, s.tasks].filter(Boolean).length / 8 * 100) : 0;
  const canRetry = !running && data.job?.status !== "completed" && data.job?.status !== "action_required";
  return <div className="space-y-6"><Link href="/problems" className="text-sm text-muted-foreground hover:text-primary">← All problems</Link>
    <div className="flex flex-col items-start justify-between gap-5 sm:flex-row"><div className="min-w-0 flex-1"><p className="text-xs font-medium text-primary">{status}</p><h1 className="mt-2 break-words text-3xl font-semibold tracking-tight">{s?.intake?.title ?? data.problem.title}</h1>{solved && data.problem.solved_at && <p className="mt-2 text-sm text-muted-foreground">Closed {new Date(data.problem.solved_at).toLocaleString()}. Reopen it to resume monitoring.</p>}</div><div className="flex flex-wrap items-start gap-2"><Button variant="outline" onClick={refresh}>Refresh status</Button><ProblemResolution id={id} solved={solved} enabled={data.job?.status === "completed"} refresh={refresh} /></div></div>
    <div className="rounded-xl border bg-card p-5"><div className="flex flex-wrap justify-between gap-2 text-sm"><p role="status">{running ? labels[s?.state ?? "PENDING"] : status}</p><span>{progress}% of analysis stages saved</span></div><div role="progressbar" aria-label="Analysis progress" aria-valuenow={progress} aria-valuemin={0} aria-valuemax={100} className="mt-3 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full bg-primary transition-all" style={{ width: `${progress}%` }} /></div><p className="mt-3 text-xs text-muted-foreground">{data.job?.status === "action_required" ? "Research is paused. Your questions are saved; submit your answers below to continue." : running ? "You can reload or leave this page. Saved progress remains in your account." : "Review the results before acting. Completing an analysis does not mean the problem is solved."}</p></div>
    {error && <p role="alert" className="text-sm text-destructive">{error} Showing the last loaded data.</p>}
    {data.humanRequest && <HumanInput key={data.humanRequest.runId} id={id} input={data.humanRequest} waiting={data.job?.status === "action_required"} refresh={refresh} />}
    <MonitoringConditions id={id} conditions={data.conditions} enabled={!solved && (data.job?.status === "completed" || data.conditions.length > 0)} problemSolved={solved} refresh={refresh} />
    {canRetry && <Panel title={data.job ? "This analysis did not finish" : "Start an analysis"} description={data.job ? "Previously saved stages remain below. Retry starts a new analysis from the beginning and counts toward your limits." : "Start the full analysis for this saved problem."}>{data.job?.error && <p className="mb-4 text-sm text-muted-foreground">Reason: {data.job.error.toLowerCase().replaceAll("_", " ")}</p>}<Button disabled={retrying} onClick={async () => {
      if (lock.current) return; lock.current = true; setRetrying(true); setRetryError(""); retryId.current ??= crypto.randomUUID();
      try { await post(`/api/problems/${id}/retry`, { requestId: retryId.current }); retryId.current = null; refresh(); }
      catch (error) { setRetryError(error instanceof Error ? error.message : "Unable to retry."); }
      finally { lock.current = false; setRetrying(false); }
    }}>{retrying ? "Starting…" : data.job ? "Retry analysis" : "Start analysis"}</Button>{retryError && <p role="alert" className="mt-3 text-sm text-destructive">{retryError}</p>}</Panel>}
    <nav aria-label="Problem sections" className="flex gap-5 overflow-x-auto border-b">{sections.map((section) => <Link key={section} href={`/problems/${id}?view=${section.toLowerCase()}`} aria-current={view === section.toLowerCase() ? "page" : undefined} className={cn("shrink-0 border-b-2 py-3 text-sm", view === section.toLowerCase() ? "border-primary text-primary" : "border-transparent text-muted-foreground")}>{section}</Link>)}</nav>
    {s?.verification && ["overview", "research", "decisions"].includes(view) && <EvidenceQuality snapshot={s} />}
    {view === "overview" && <div className="grid gap-5 lg:grid-cols-2"><Panel title="The outcome"><p className="whitespace-pre-wrap break-words leading-relaxed">{s?.intake?.goal ?? data.problem.original_input}</p>{s?.intake && <p className="mt-4 text-sm text-muted-foreground">{s.intake.initialAssessment}</p>}</Panel><Panel title="Recommendation" description={s?.decision ? `Confidence: ${s.decision.confidence}` : undefined}>{s?.decision ? <><p className="leading-relaxed">{s.decision.recommendation}</p><p className="mt-4 text-sm text-muted-foreground">{s.decision.reasoningSummary}</p></> : <p className="text-sm text-muted-foreground">No recommendation has been saved yet.</p>}</Panel>{s?.intake && <><Panel title="Constraints"><TextList items={s.intake.constraints} /></Panel><Panel title="Open questions" description={s.human?.responses ? "Originally identified unknowns. Your saved responses provide additional context; remaining uncertainty is reflected in the recommendation." : "Unknown information identified at intake."}><TextList items={s.intake.unknowns} /></Panel><Panel title="Known facts"><TextList items={s.intake.knownFacts} /></Panel><Panel title="Assumptions"><TextList items={s.intake.assumptions} /></Panel></>}<Panel title="Agent activity"><ol className="space-y-3 text-sm">{s?.events.map((event, index) => <li key={index}><span className="font-medium">{event.state === "RESEARCH" && s.events[index + 1]?.state === "ACTION_REQUIRED" ? "Initial plan saved" : labels[event.state]}</span><span className="ml-3 text-xs text-muted-foreground">{new Date(event.at).toLocaleTimeString()}</span></li>) ?? <li>Waiting for the first saved checkpoint.</li>}</ol></Panel>{data.lifecycle.length > 0 && <Panel title="Problem history"><ol className="space-y-3 text-sm">{data.lifecycle.map((event) => <li key={event.id}><span className="font-medium">{event.event === "solved" ? "Marked solved" : "Reopened"}</span><span className="ml-3 text-xs text-muted-foreground">{new Date(event.createdAt).toLocaleString()}</span></li>)}</ol></Panel>}</div>}
    {view === "plan" && (s?.plan ? <Panel title="The plan"><ol className="space-y-5">{s.plan.steps.map((step, index) => <li key={step.id} className="rounded-lg border p-4"><h3 className="font-semibold">{index + 1}. {step.title}</h3><p className="mt-2 text-sm">{step.description}</p><p className="mt-2 text-xs text-muted-foreground">Priority: {step.priority} · Dependencies: {step.dependencies.join(", ") || "None"}</p>{step.researchQuestions.length > 0 && <div className="mt-3"><p className="mb-2 text-sm font-medium">Research questions</p><TextList items={step.researchQuestions} /></div>}{step.userQuestions.length > 0 && <div className="mt-3"><p className="mb-2 text-sm font-medium">Questions for you</p><TextList items={step.userQuestions} /></div>}</li>)}</ol></Panel> : <Missing />)}
    {view === "research" && (s?.research ? <div className="space-y-5"><Panel title="Research notes" description={`${investigated.length} priority ${investigated.length===1?"question":"questions"} investigated`}><div className="mb-4"><TextList items={investigated} /></div><p className="text-sm leading-relaxed">{s.research.output.summary}</p><div className="mt-4"><TextList items={s.research.output.limitations} /></div><p className="mt-4 text-xs text-muted-foreground">{plannedResearch>investigated.length ? `${plannedResearch-investigated.length} additional planned ${plannedResearch-investigated.length===1?"question remains":"questions remain"} open.` : "All planned research questions were included in this bounded run."}</p></Panel><Panel title="Evidence register"><div className="space-y-5">{s.research.output.claims.map((claim) => { const assessment = s.verification?.assessments.find((item) => item.claimId === claim.id); return <article key={claim.id} className="rounded-lg border p-4"><p className="font-medium">{claim.statement}</p><p className="mt-2 text-xs text-primary">{assessment?.status.replaceAll("_", " ") ?? "NOT ASSESSED"} · Model assessment</p>{assessment && <><p className="mt-2 text-sm">{assessment.summary}</p><p className="mt-2 text-xs text-muted-foreground">Quality: {assessment.sourceQuality} · Freshness: {assessment.freshness}</p><TextList items={assessment.contradictions} /></>}<div className="mt-3 flex flex-wrap gap-3">{claim.sourceIds.map((sourceId) => { const source = s.research!.sources.find((item) => item.id === sourceId); return source && <a key={sourceId} className="break-all text-sm text-primary underline" href={source.url} target="_blank" rel="noopener noreferrer">{source.title}</a>; })}</div></article>; })}{!s.research.output.claims.length && <p className="text-sm text-muted-foreground">No supported claims were returned.</p>}</div></Panel><Panel title="Retrieved sources"><div className="space-y-5">{s.research.sources.map((source) => <article key={source.id} className="min-w-0"><a className="break-words font-medium text-primary underline" href={source.url} target="_blank" rel="noopener noreferrer">{source.title}</a><p className="mt-2 break-all text-xs text-muted-foreground">{source.url}</p><p className="mt-2 text-xs text-muted-foreground">Retrieved {new Date(source.retrievedAt).toLocaleString()} · {source.publishedAt ? `Publication date reported by search: ${new Date(source.publishedAt).toLocaleDateString()}` : "Publication date not established"}</p><details className="mt-3 text-sm"><summary className="cursor-pointer">Read source excerpt</summary><p className="mt-3 whitespace-pre-wrap break-words leading-relaxed">{source.content}</p></details></article>)}</div></Panel></div> : <Missing />)}
    {view === "options" && (s?.options ? <Panel title="Options to consider"><div className="grid gap-4 md:grid-cols-2">{s.options.options.map((option) => <article key={option.id} className="rounded-lg border p-4"><h3 className="font-semibold">{option.title}</h3>{s.decision?.selectedOptionId === option.id && <p className="mt-2 text-xs font-medium text-primary">Recommended for review</p>}<p className="my-3 text-sm leading-relaxed">{option.description}</p><TextList items={option.risks} /></article>)}</div><div className="mt-4"><TextList items={s.options.limitations} /></div>{!s.options.options.length && <p className="mt-3 text-sm">No viable options were proposed.</p>}</Panel> : <Missing />)}
    {view === "risks" && (s?.critique ? <div className="grid gap-5 md:grid-cols-2"><Panel title="Critic review"><p className="text-sm leading-relaxed">{s.critique.summary}</p></Panel>{[{ title: "Risks", items: s.critique.risks }, { title: "Failure scenarios", items: s.critique.failureScenarios }, { title: "Overlooked constraints", items: s.critique.overlookedConstraints }, { title: "Unsupported assumptions", items: s.critique.unsupportedAssumptions }, { title: "Evidence weaknesses", items: s.critique.evidenceWeaknesses }, { title: "Other approaches", items: s.critique.alternativeSuggestions }].map((group) => <Panel title={group.title} key={group.title}><TextList items={group.items} /></Panel>)}</div> : <Missing />)}
    {view === "tasks" && <div className="space-y-5">{s?.tasks ? <Panel title="Action plan" description="Track your progress here. Status changes are saved, but Avenli never executes a task or external action automatically."><TaskList problemId={id} generated={s.tasks.tasks} saved={data.tasks} refresh={refresh} /></Panel> : <Missing />}<CalendarActions id={id} title={s?.intake?.title??data.problem.title} actions={data.actions} access={data.actionAccess} analysisComplete={data.job?.status==="completed"} refresh={refresh} /></div>}
    {view === "decisions" && (s?.decision ? <div className="space-y-5"><Panel title="Decision trail" description={`Confidence: ${s.decision.confidence}`}><p className="font-medium">{s.decision.recommendation}</p><p className="mt-3 text-sm leading-relaxed">{s.decision.reasoningSummary}</p>{s.decision.selectedOptionId === null && <p className="mt-4 text-sm text-muted-foreground">No option selected. More information is needed.</p>}<div className="mt-4 flex flex-wrap gap-3">{s.decision.supportingEvidence.map((id) => { const source = s.research?.sources.find((item) => item.id === id); return source && <a key={id} className="text-sm text-primary underline" href={source.url} target="_blank" rel="noopener noreferrer">{source.title}</a>; })}</div></Panel><Panel title="Assumptions"><TextList items={s.decision.assumptions} /></Panel><Panel title="Unresolved unknowns" description="Start a separate focused analysis for a question that materially affects this recommendation. This uses one of your analysis attempts and never performs an external action.">{s.decision.unresolvedUnknowns.length ? <ul className="space-y-3">{s.decision.unresolvedUnknowns.map((unknown, index) => <FollowUpAnalysis key={`${index}-${unknown}`} goal={s.intake?.goal ?? data.problem.original_input} unknown={unknown} disabled={running} />)}</ul> : <p className="text-sm text-muted-foreground">None recorded.</p>}</Panel><Panel title="Rejected alternatives"><TextList items={s.decision.rejectedAlternatives.map((item) => `${s.options?.options.find((option) => option.id === item.optionId)?.title ?? item.optionId}: ${item.reason}`)} /></Panel></div> : <Missing />)}
  </div>;
}
