"use client";
import { useEffect, useRef, useState, useSyncExternalStore } from "react";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Panel, EmptyState } from "@/components/demo/primitives";
import { detailSchema, jobActive, jobLabel, type ProblemDetail } from "@/lib/workspace/contracts";
import { post, useRemote } from "./remote";
import { EvidenceQuality } from "./evidence-quality";
import { HumanInput } from "./human-input";
import { MonitoringConditions } from "./monitoring-conditions";
import { CalendarActions } from "./calendar-actions";
import { TaskList } from "./task-list";
import { ProblemResolution } from "./problem-resolution";
import { FollowUpAnalysis } from "./follow-up-analysis";
import { cn } from "@/lib/utils";
import { LoadingSkeleton } from "./loading-skeleton";
import { AnalysisProgress } from "./analysis-progress";
import { ui, uiStatus, useCzech } from "./ui-language";
const active = (value: ProblemDetail) => value.problem.status !== "solved" && (jobActive(value.job) || value.conditions.some((condition) => condition.status === "checking"));
const sections = ["Overview", "Questions", "Plan", "Research", "Options", "Risks", "Tasks", "Decisions"];
const czechSections: Record<string, string> = { Overview:"Přehled", Questions:"Dotazy", Plan:"Plán", Research:"Zdroje", Options:"Možnosti", Risks:"Rizika", Tasks:"Úkoly", Decisions:"Rozhodnutí" };
const labels: Record<string, string> = { ACTION_REQUIRED: "Waiting for your answers", RESUME: "Updating the plan with your answers", PENDING: "Queued", INTAKE: "Understanding your problem", PLAN: "Building a plan", RESEARCH: "Researching priority questions", VERIFY: "Checking evidence", OPTIONS: "Comparing approaches", CRITIQUE: "Challenging the plan", DECIDE: "Preparing a recommendation", TASKS: "Drafting tasks", COMPLETED: "Analysis complete", FAILED: "Analysis stopped", CANCELLED: "Analysis stopped" };
function TextList({ items }: { items: string[] }) { const cs=useCzech(); return items.length ? <ul className="space-y-2 text-sm leading-relaxed">{items.map((text, index) => <li className="break-words" key={index}>• {text}</li>)}</ul> : <p className="text-sm text-muted-foreground">{ui(cs,"None recorded.","Nic zde není.")}</p>; }
function Missing() { const cs=useCzech(); return <EmptyState title={ui(cs,"No saved result for this stage yet","Pro tento krok zatím není výsledek")} detail={ui(cs,"Results appear here after the stage finishes.","Výsledky se objeví po dokončení kroku.")} />; }
const progressSubscribe = (notify: () => void) => { window.addEventListener("avenli-progress", notify); return () => window.removeEventListener("avenli-progress", notify); };
const progressSnapshot = () => sessionStorage.getItem("avenli-progress-id");

export function LiveProblem({ id }: { id: string }) {
  const { data, error, refresh } = useRemote(`/api/problems/${id}`, detailSchema, active);
  const progressId = useSyncExternalStore(progressSubscribe, progressSnapshot, () => null);
  const cs = useCzech(); const router = useRouter();
  const search = useSearchParams(); const raw = search.get("view") ?? "overview"; const view = sections.some((section) => section.toLowerCase() === raw) ? raw : "overview";
  const [retryError, setRetryError] = useState(""); const [retrying, setRetrying] = useState(false); const retryId = useRef<string | null>(null); const lock = useRef(false);
  useEffect(() => {
    if (data?.job?.status === "action_required" && view !== "questions" && progressId !== id) router.replace(`/problems/${id}?view=questions`);
  }, [data?.job?.status, id, progressId, router, view]);
  if (!data) return <>{error ? <div role="alert" className="avenli-panel rounded-xl p-5">{error}<Button className="ml-3" variant="outline" onClick={refresh}>{ui(cs,"Retry","Zkusit znovu")}</Button></div> : <LoadingSkeleton detail />}{progressId === id && <AnalysisProgress problemId={id} />}</>;
  const s = data.snapshot; const running = jobActive(data.job); const solved = data.problem.status === "solved"; const status = uiStatus(cs, solved ? "Solved" : jobLabel(data.job));
  const investigated=s?.research?.questions ?? (s?.research ? [s.research.question] : []); const plannedResearch=new Set(s?.plan?.steps.flatMap((step)=>step.researchQuestions)??[]).size;
  const progress = s ? Math.round([s.intake, s.plan, s.research, s.verification, s.options, s.critique, s.decision, s.tasks].filter(Boolean).length / 8 * 100) : 0;
  const canRetry = !running && data.job?.status !== "completed" && data.job?.status !== "action_required";
  return <div className="space-y-4">{progressId === id && <AnalysisProgress problemId={id} />}<Link href="/problems" className="text-xs font-medium text-muted-foreground transition hover:text-primary">← {ui(cs,"All problems","Všechna zadání")}</Link>
    <div className="flex flex-col items-start justify-between gap-3 sm:flex-row"><div className="min-w-0 flex-1"><p className="inline-flex rounded-full bg-secondary px-2.5 py-1 text-[11px] font-semibold text-secondary-foreground">{status}</p><h1 className="mt-2 break-words text-[1.8rem] font-semibold leading-tight tracking-[-.045em] text-[#0e1450] sm:text-[2.15rem]">{s?.intake?.title ?? data.problem.title}</h1>{solved && data.problem.solved_at && <p className="mt-2 text-xs text-muted-foreground">{ui(cs,"Closed","Uzavřeno")} {new Date(data.problem.solved_at).toLocaleString(cs ? "cs-CZ" : "en-US")}. {ui(cs,"Reopen it to resume monitoring.","Pro obnovení sledování zadání znovu otevřete.")}</p>}</div><div className="flex flex-wrap items-start gap-2"><Button variant="outline" size="sm" onClick={refresh}>{ui(cs,"Refresh status","Obnovit stav")}</Button><ProblemResolution id={id} solved={solved} enabled={data.job?.status === "completed"} refresh={refresh} /></div></div>
    {(running || data.job?.status === "action_required") && <div className="avenli-panel rounded-2xl p-4"><div className="flex flex-wrap justify-between gap-2 text-sm"><p role="status" className="font-medium text-[#151955]">{running ? ui(cs,labels[s?.state ?? "PENDING"],({PENDING:"Ve frontě",INTAKE:"Rozumím zadání",PLAN:"Připravuji plán",RESEARCH:"Zkoumám zdroje",VERIFY:"Ověřuji informace",OPTIONS:"Porovnávám možnosti",CRITIQUE:"Prověřuji rizika",DECIDE:"Připravuji doporučení",TASKS:"Připravuji kroky",RESUME:"Zapracovávám odpovědi"} as Record<string,string>)[s?.state ?? "PENDING"] ?? "Probíhá analýza") : status}</p><span className="text-muted-foreground">{ui(cs,`${Math.round(progress / 12.5)} of 8 stages saved`,`${Math.round(progress / 12.5)} z 8 kroků uloženo`)}</span></div><div role="progressbar" aria-label="Analysis progress" aria-valuenow={progress} aria-valuemin={0} aria-valuemax={100} className="mt-2 h-1.5 overflow-hidden rounded-full bg-[#edf0f8]"><div className="h-full rounded-full bg-[linear-gradient(90deg,#4358f4,#7b3cf1)] transition-all" style={{ width: `${progress}%` }} /></div></div>}
    {view !== "questions" && (data.job?.status === "action_required" || running || !s?.decision) && <section className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-primary/20 bg-[linear-gradient(110deg,#f1f2ff,#fbfaff)] px-4 py-3.5" aria-label={ui(cs,"What to do next","Co dělat dál")}><div><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-primary">{ui(cs,"What to do next","Co dělat dál")}</p><h2 className="mt-1 text-sm font-semibold">{data.job?.status === "action_required" ? ui(cs,"Answer Avenli's questions","Odpovězte na doplňující dotazy") : running ? ui(cs,"Analysis is still running","Analýza stále probíhá") : ui(cs,"Review the saved work or retry","Projděte uloženou práci nebo opakujte analýzu")}</h2><p className="mt-0.5 text-xs text-muted-foreground">{data.job?.status === "action_required" ? ui(cs,"The workflow pauses here until you respond.","Analýza zde počká, dokud neodpovíte.") : running ? ui(cs,"Progress is saved. You can return later.","Postup je uložený. Můžete se vrátit později.") : ui(cs,"You can inspect the last saved step below.","Níže si můžete projít poslední uložený krok.")}</p></div>{data.job?.status === "action_required" && <Button asChild size="sm"><Link href={`/problems/${id}?view=questions`}>{ui(cs,"Answer questions","Odpovědět na dotazy")}</Link></Button>}</section>}
    {error && <p role="alert" className="text-sm text-destructive">{error} Showing the last loaded data.</p>}
    <nav aria-label="Problem sections" className="flex flex-wrap items-center gap-1 rounded-xl border bg-white/80 p-1.5">{sections.filter((section)=>["Overview","Research","Tasks","Questions"].includes(section) && (section!=="Questions" || Boolean(data.humanRequest))).map((section) => <Link key={section} href={`/problems/${id}?view=${section.toLowerCase()}`} aria-current={view === section.toLowerCase() ? "page" : undefined} className={cn("rounded-lg px-3 py-2 text-sm font-medium transition", view === section.toLowerCase() ? "bg-[#edefff] text-primary shadow-sm" : "text-muted-foreground hover:bg-white hover:text-foreground")}>{cs ? czechSections[section] : section}</Link>)}<select aria-label={ui(cs,"More sections","Další části")} value={["plan","options","risks","decisions"].includes(view) ? view : ""} onChange={(event)=>{if(event.target.value) router.push(`/problems/${id}?view=${event.target.value}`);}} className={cn("ml-auto h-9 rounded-lg border-0 bg-transparent px-2 text-sm font-medium text-muted-foreground", ["plan","options","risks","decisions"].includes(view) && "bg-[#edefff] text-primary") }><option value="">{ui(cs,"More details","Podrobnosti")}</option>{["Plan","Options","Risks","Decisions"].map((section)=><option key={section} value={section.toLowerCase()}>{cs ? czechSections[section] : section}</option>)}</select></nav>
    {data.humanRequest && view === "questions" && <HumanInput key={data.humanRequest.runId} id={id} input={data.humanRequest} waiting={data.job?.status === "action_required"} refresh={refresh} />}
    {canRetry && <Panel title={data.job ? "This analysis did not finish" : "Start an analysis"} description={data.job ? "Previously saved stages remain below. Retry starts a new analysis from the beginning and counts toward your limits." : "Start the full analysis for this saved problem."}>{data.job?.error && <p className="mb-4 text-sm text-muted-foreground">Reason: {data.job.error.toLowerCase().replaceAll("_", " ")}</p>}<Button disabled={retrying} onClick={async () => {
      if (lock.current) return; lock.current = true; setRetrying(true); setRetryError(""); retryId.current ??= crypto.randomUUID();
      try { await post(`/api/problems/${id}/retry`, { requestId: retryId.current }); retryId.current = null; refresh(); }
      catch (error) { setRetryError(error instanceof Error ? error.message : "Unable to retry."); }
      finally { lock.current = false; setRetrying(false); }
    }}>{retrying ? "Starting…" : data.job ? "Retry analysis" : "Start analysis"}</Button>{retryError && <p role="alert" className="mt-3 text-sm text-destructive">{retryError}</p>}</Panel>}

    {view === "questions" && !data.humanRequest && <EmptyState title={ui(cs,"No questions right now","Nyní nemáme žádné dotazy")} detail={ui(cs,"You can continue reviewing the saved result.","Můžete si dál procházet uložený výsledek.")} />}
    {s?.verification && ["research", "decisions"].includes(view) && <details className="rounded-[1.25rem] border bg-white/80 p-5"><summary className="cursor-pointer font-semibold">{ui(cs,"Evidence quality and detailed checks","Kvalita zdrojů a podrobné ověření")}</summary><div className="mt-4"><EvidenceQuality snapshot={s} /></div></details>}
    {view === "overview" && <div className="grid items-start gap-4 xl:grid-cols-[minmax(0,1.65fr)_minmax(250px,.7fr)]">
      <div className="space-y-4">
        <Panel title={ui(cs,"Result","Výsledek")} description={s?.decision ? ui(cs,"Confidence: " + s.decision.confidence,"Míra jistoty: " + s.decision.confidence) : undefined} className={s?.decision ? "border-primary/20 bg-[linear-gradient(145deg,#fff,#f6f5ff)]" : undefined}>
          {s?.decision ? <><p className="text-lg font-semibold leading-relaxed text-[#151955]">{s.decision.recommendation}</p><details className="mt-4 text-sm text-muted-foreground"><summary className="cursor-pointer font-medium text-primary">{ui(cs,"Why this result?","Proč tento výsledek?")}</summary><p className="mt-3 leading-relaxed">{s.decision.reasoningSummary}</p></details><div className="mt-5 flex flex-wrap gap-2"><Button asChild size="sm"><Link href={"/problems/" + id + "?view=tasks"}>{ui(cs,"See next steps","Zobrazit další kroky")}</Link></Button><Button asChild size="sm" variant="outline"><Link href={"/problems/" + id + "?view=research"}>{ui(cs,"Check sources","Ověřit zdroje")}</Link></Button></div></> : <><p className="text-sm text-muted-foreground">{s?.research ? ui(cs,"Research is saved. The recommendation is still being prepared.","Výzkum je uložený. Doporučení se ještě připravuje.") : ui(cs,"The result will appear here after the analysis finishes.","Výsledek se zobrazí po dokončení analýzy.")}</p>{s?.research && <Link className="mt-3 inline-block text-sm font-medium text-primary underline" href={"/problems/" + id + "?view=research"}>{ui(cs,"Review saved research","Prohlédnout uložený výzkum")}</Link>}</>}</Panel>
        <details className="avenli-panel rounded-2xl px-4 py-3.5"><summary className="cursor-pointer text-sm font-semibold">{ui(cs,"Your goal","Váš cíl")}</summary><p className="mt-3 whitespace-pre-wrap break-words border-t pt-3 text-sm leading-relaxed">{s?.intake?.goal ?? data.problem.original_input}</p></details>
        {s?.intake && <details className="avenli-panel rounded-[1.25rem] p-5"><summary className="cursor-pointer font-semibold">{ui(cs,"Facts, constraints and assumptions","Fakta, omezení a předpoklady")}</summary><div className="mt-5 grid gap-5 text-sm sm:grid-cols-2"><div><h3 className="font-semibold">{ui(cs,"Known facts","Známá fakta")}</h3><TextList items={s.intake.knownFacts} /></div><div><h3 className="font-semibold">{ui(cs,"Constraints","Omezení")}</h3><TextList items={s.intake.constraints} /></div><div><h3 className="font-semibold">{ui(cs,"Open questions","Otevřené otázky")}</h3><TextList items={s.intake.unknowns} /></div><div><h3 className="font-semibold">{ui(cs,"Assumptions","Předpoklady")}</h3><TextList items={s.intake.assumptions} /></div></div></details>}
      </div>
      <div className="space-y-4">
        {s?.decision?.unresolvedUnknowns?.length ? <Panel title={ui(cs,"Still to clarify","Zbývá upřesnit")}><p className="text-sm text-muted-foreground">{s.decision.unresolvedUnknowns.length} {ui(cs,"important questions remain. Open Decision to investigate them.","důležitých otázek zůstává. Otevřete Rozhodnutí a prozkoumejte je.")}</p><Link className="mt-3 inline-block text-sm font-medium text-primary underline" href={"/problems/" + id + "?view=decisions"}>{ui(cs,"View unknowns","Zobrazit otázky")}</Link></Panel> : null}
        <details className="avenli-panel rounded-[1.25rem] p-5"><summary className="cursor-pointer font-semibold">{ui(cs,"Monitoring (optional)","Sledování změn (volitelné)")}{data.conditions.length ? " · " + data.conditions.length : ""}</summary><div className="mt-4"><MonitoringConditions id={id} conditions={data.conditions} enabled={!solved && (data.job?.status === "completed" || data.conditions.length > 0)} problemSolved={solved} refresh={refresh} /></div></details>
        <details className="avenli-panel rounded-[1.25rem] p-5"><summary className="cursor-pointer font-semibold">{ui(cs,"Analysis activity","Průběh analýzy")}</summary><ol className="mt-4 space-y-3 text-sm">{s?.events.map((event, index) => <li key={index} className="flex items-center justify-between gap-4"><span>{labels[event.state]}</span><time className="shrink-0 text-xs text-muted-foreground">{new Date(event.at).toLocaleTimeString(cs ? "cs-CZ" : "en-US")}</time></li>) ?? <li>{ui(cs,"Waiting for the first checkpoint.","Čekám na první uložený krok.")}</li>}</ol></details>
        {data.lifecycle.length > 0 && <details className="avenli-panel rounded-[1.25rem] p-5"><summary className="cursor-pointer font-semibold">{ui(cs,"Problem history","Historie zadání")}</summary><ol className="mt-4 space-y-3 text-sm">{data.lifecycle.map((event) => <li key={event.id}>{event.event === "solved" ? ui(cs,"Marked solved","Označeno jako vyřešené") : ui(cs,"Reopened","Znovu otevřeno")} · {new Date(event.createdAt).toLocaleString(cs ? "cs-CZ" : "en-US")}</li>)}</ol></details>}
      </div>
    </div>}    {view === "plan" && (s?.plan ? <Panel title={ui(cs,"The plan","Plán")}><ol className="space-y-5">{s.plan.steps.map((step, index) => <li key={step.id} className="rounded-lg border p-4"><h3 className="font-semibold">{index + 1}. {step.title}</h3><p className="mt-2 text-sm">{step.description}</p><p className="mt-2 text-xs text-muted-foreground">Priority: {step.priority} · Dependencies: {step.dependencies.join(", ") || "None"}</p>{step.researchQuestions.length > 0 && <div className="mt-3"><p className="mb-2 text-sm font-medium">Research questions</p><TextList items={step.researchQuestions} /></div>}{step.userQuestions.length > 0 && <div className="mt-3"><p className="mb-2 text-sm font-medium">Questions for you</p><TextList items={step.userQuestions} /></div>}</li>)}</ol></Panel> : <Missing />)}
    {view === "research" && (s?.research ? <div className="space-y-4">
      <Panel title={ui(cs,"Research summary","Shrnutí výzkumu")} description={ui(cs,investigated.length + " research questions explored",investigated.length + " prozkoumaných otázek")}><p className="text-sm leading-relaxed">{s.research.output.summary}</p>{plannedResearch > investigated.length && <p className="mt-3 text-xs text-amber-800">{ui(cs,"Some planned questions were outside this bounded search.","Některé plánované otázky nebyly součástí tohoto omezeného vyhledávání.")}</p>}{s.research.output.limitations.length > 0 && <details className="mt-4 text-sm"><summary className="cursor-pointer font-medium text-primary">{ui(cs,"What remains uncertain","Co zůstává nejisté")}</summary><div className="mt-3"><TextList items={s.research.output.limitations} /></div></details>}</Panel>
      <Panel title={ui(cs,"Evidence at a glance","Přehled tvrzení")} description={ui(cs,"Open a claim to see its assessment and linked sources.","Otevřete tvrzení pro posouzení a související zdroje.")}><div className="space-y-2">{s.research.output.claims.map((claim) => { const assessment=s.verification?.assessments.find((item)=>item.claimId===claim.id); const status=assessment?.status ?? "NOT ASSESSED"; const statusLabel=cs ? ({VERIFIED:"Ověřeno",UNVERIFIED:"Neověřeno",CONFLICTING:"Rozpor ve zdrojích","NOT ASSESSED":"Neposouzeno"} as Record<string,string>)[status] : status.replaceAll("_"," "); return <details key={claim.id} className="rounded-xl border bg-white px-4 py-3"><summary className="cursor-pointer list-none"><span className="mb-1 block text-[11px] font-semibold uppercase tracking-wide text-primary">{statusLabel}</span><span className="text-sm font-medium">{claim.statement}</span></summary><div className="mt-3 border-t pt-3 text-sm text-muted-foreground">{assessment?.summary && <p>{assessment.summary}</p>}<div className="mt-3 flex flex-wrap gap-3">{claim.sourceIds.map((sourceId)=>{const source=s.research!.sources.find((item)=>item.id===sourceId);return source && <a key={sourceId} className="break-words text-primary underline" href={source.url} target="_blank" rel="noopener noreferrer">{source.title}</a>;})}</div></div></details>;})}{!s.research.output.claims.length && <p className="text-sm text-muted-foreground">{ui(cs,"No supported claims were returned.","Výzkum nevrátil podložená tvrzení.")}</p>}</div></Panel>
      <details className="avenli-panel rounded-[1.25rem] p-5"><summary className="cursor-pointer font-semibold">{ui(cs,"Retrieved sources (" + s.research.sources.length + ")","Načtené zdroje (" + s.research.sources.length + ")")}</summary><div className="mt-5 space-y-4">{s.research.sources.map((source)=><article key={source.id} className="min-w-0 border-t pt-4"><a className="break-words font-medium text-primary underline" href={source.url} target="_blank" rel="noopener noreferrer">{source.title}</a><p className="mt-1 break-all text-xs text-muted-foreground">{source.url}</p><details className="mt-2 text-sm"><summary className="cursor-pointer text-primary">{ui(cs,"Read excerpt","Zobrazit úryvek")}</summary><p className="mt-2 whitespace-pre-wrap break-words leading-relaxed">{source.content}</p></details></article>)}</div></details>
    </div> : <Missing />)}
    {view === "options" && (s?.options ? <Panel title={ui(cs,"Options to consider","Možnosti k posouzení")}><div className="grid gap-4 md:grid-cols-2">{s.options.options.map((option) => <article key={option.id} className="rounded-lg border p-4"><h3 className="font-semibold">{option.title}</h3>{s.decision?.selectedOptionId === option.id && <p className="mt-2 text-xs font-medium text-primary">{ui(cs,"Recommended for review","Doporučeno k posouzení")}</p>}<p className="my-3 text-sm leading-relaxed">{option.description}</p><TextList items={option.risks} /></article>)}</div><div className="mt-4"><TextList items={s.options.limitations} /></div>{!s.options.options.length && <p className="mt-3 text-sm">{ui(cs,"No viable options were proposed.","Nebyly nalezeny použitelné možnosti.")}</p>}</Panel> : <Missing />)}
    {view === "risks" && (s?.critique ? <div className="grid gap-5 md:grid-cols-2"><Panel title={ui(cs,"Critic review","Kontrola návrhu")}><p className="text-sm leading-relaxed">{s.critique.summary}</p></Panel>{[{ title: ui(cs,"Risks","Rizika"), items: s.critique.risks }, { title: ui(cs,"Failure scenarios","Možná selhání"), items: s.critique.failureScenarios }, { title: ui(cs,"Overlooked constraints","Přehlédnutá omezení"), items: s.critique.overlookedConstraints }, { title: ui(cs,"Unsupported assumptions","Nepodložené předpoklady"), items: s.critique.unsupportedAssumptions }, { title: ui(cs,"Evidence weaknesses","Slabiny zdrojů"), items: s.critique.evidenceWeaknesses }, { title: ui(cs,"Other approaches","Jiné přístupy"), items: s.critique.alternativeSuggestions }].map((group) => <Panel title={group.title} key={group.title}><TextList items={group.items} /></Panel>)}</div> : <Missing />)}
    {view === "tasks" && <div className="space-y-5">{s?.tasks ? <Panel title={ui(cs,"Action plan","Další kroky")} description={ui(cs,"Track your progress. Avenli never executes these tasks automatically.","Sledujte postup. Avenli tyto úkoly nikdy neprovádí automaticky.")}><TaskList problemId={id} generated={s.tasks.tasks} saved={data.tasks} refresh={refresh} /></Panel> : <Missing />}<CalendarActions id={id} title={s?.intake?.title??data.problem.title} actions={data.actions} access={data.actionAccess} analysisComplete={data.job?.status==="completed"} refresh={refresh} /></div>}
    {view === "decisions" && (s?.decision ? <div className="space-y-5"><Panel title={ui(cs,"Decision trail","Vysvětlení rozhodnutí")} description={`Confidence: ${s.decision.confidence}`}><p className="font-medium">{s.decision.recommendation}</p><p className="mt-3 text-sm leading-relaxed">{s.decision.reasoningSummary}</p>{s.decision.selectedOptionId === null && <p className="mt-4 text-sm text-muted-foreground">{ui(cs,"No option selected. More information is needed.","Zatím nelze vybrat možnost. Je potřeba doplnit informace.")}</p>}<div className="mt-4 flex flex-wrap gap-3">{s.decision.supportingEvidence.map((id) => { const source = s.research?.sources.find((item) => item.id === id); return source && <a key={id} className="text-sm text-primary underline" href={source.url} target="_blank" rel="noopener noreferrer">{source.title}</a>; })}</div></Panel><Panel title={ui(cs,"Assumptions","Předpoklady")}><TextList items={s.decision.assumptions} /></Panel><Panel title={ui(cs,"Unresolved unknowns","Nezodpovězené otázky")} description={ui(cs,"Explore an important question in a separate analysis.","Důležitou otázku můžete prozkoumat v samostatné analýze.")}>{s.decision.unresolvedUnknowns.length ? <ul className="space-y-3">{s.decision.unresolvedUnknowns.map((unknown, index) => <FollowUpAnalysis key={`${index}-${unknown}`} goal={s.intake?.goal ?? data.problem.original_input} unknown={unknown} disabled={running} />)}</ul> : <p className="text-sm text-muted-foreground">None recorded.</p>}</Panel><Panel title={ui(cs,"Rejected alternatives","Odmítnuté možnosti")}><TextList items={s.decision.rejectedAlternatives.map((item) => `${s.options?.options.find((option) => option.id === item.optionId)?.title ?? item.optionId}: ${item.reason}`)} /></Panel></div> : <Missing />)}
  </div>;
}
