"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowRight, CalendarClock, CircleHelp, CheckCircle2, Clock3, FolderKanban, Plus, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { EmptyState, PageHeading } from "@/components/demo/primitives";
import { useDemo } from "@/components/demo/demo-provider";
import { jobActive, listSchema, problemLabel, type ProblemList } from "@/lib/workspace/contracts";
import { useRemote } from "./remote";
import { LoadingSkeleton } from "./loading-skeleton";
import { ui, uiStatus, useCzech } from "./ui-language";

const active = (list: ProblemList) => list.some((item) => item.problem.status !== "solved" && jobActive(item.job));

export function LiveProblemList({ overview = false }: { overview?: boolean }) {
  const { account } = useDemo();
  const cs = useCzech();
  const { data, error, refresh } = useRemote("/api/problems", listSchema, active);
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState("All");
  const filtered = (data ?? []).filter(({ problem, job }) =>
    (problem.title + problem.original_input).toLowerCase().includes(search.toLowerCase()) &&
    (status === "All" || problemLabel(problem, job) === status));
  const ready = (data ?? []).filter(({ problem, job }) => problemLabel(problem, job) === "Ready to review").length;
  const waiting = (data ?? []).filter(({ problem, job }) => problemLabel(problem, job) === "Needs your input").length;
  const activeCount = (data ?? []).filter(({ problem, job }) => problem.status !== "solved" && jobActive(job)).length;
  const dueTasks = (data ?? []).reduce((total, item) => total + item.dueTaskCount, 0);
  const recent = filtered.slice(0, overview ? 6 : 100);

  return <div className="space-y-5">
    <PageHeading eyebrow={overview ? ui(cs,"Your workspace","Váš prostor") : ui(cs,"Problems","Zadání")} title={overview ? `${ui(cs,"Welcome","Vítejte")}${account.displayName ? `, ${account.displayName}` : ""}` : ui(cs,"Your problems","Vaše zadání")} description={ui(cs,"Find what needs your attention and open the saved result.","Najděte, co potřebuje vaši pozornost, a otevřete uložený výsledek.")} action={Boolean(data?.length)} />
    {overview && data && data.length > 0 && <div className="grid grid-cols-2 gap-2.5 sm:gap-3 xl:grid-cols-5">{[
      { label: ui(cs,"Problems","Zadání"), value: data?.length ?? "—", icon: FolderKanban },
      { label: ui(cs,"In progress","Probíhá"), value: data ? activeCount : "—", icon: Clock3 },
      { label: ui(cs,"Need your input","Čeká na vás"), value: data ? waiting : "—", icon: CircleHelp },
      { label: ui(cs,"Ready to review","K posouzení"), value: data ? ready : "—", icon: CheckCircle2 },
      { label: ui(cs,"Due soon","Brzy splatné"), value: data ? dueTasks : "—", icon: CalendarClock },
    ].map(({ label, value, icon: Icon }) => <div key={label} className="avenli-panel flex items-center justify-between rounded-[1.15rem] p-3 sm:p-4 last:col-span-2 xl:last:col-span-1"><div><p className="text-xs font-medium text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-semibold tracking-[-.04em] text-[#111653]">{value}</p></div><span className="flex size-8 shrink-0 items-center justify-center rounded-xl bg-[#eff0ff] text-[#4d42e6]"><Icon className="size-[17px]" aria-hidden="true" /></span></div>)}</div>}
    {!overview && Boolean(data?.length) && <div className="flex flex-wrap gap-2"><input aria-label={ui(cs,"Search problems","Hledat zadání")} value={search} onChange={(event) => setSearch(event.target.value)} placeholder={ui(cs,"Search your problems","Hledat v zadáních")} className="h-10 min-w-0 flex-1 rounded-xl border bg-white/90 px-3.5 shadow-sm" /><select aria-label={ui(cs,"Status","Stav")} value={status} onChange={(event) => setStatus(event.target.value)} className="h-10 rounded-xl border bg-white/90 px-3.5 shadow-sm">{["All", "Queued", "Analyzing", "Needs your input", "Ready to review", "Solved", "Needs retry", "Interrupted", "Not started"].map((item) => <option key={item} value={item}>{ui(cs,item,({All:"Vše",Queued:"Ve frontě",Analyzing:"Probíhá", "Needs your input":"Čeká na odpověď", "Ready to review":"K posouzení",Solved:"Vyřešeno","Needs retry":"Zkusit znovu",Interrupted:"Přerušeno","Not started":"Nezahájeno"} as Record<string,string>)[item])}</option>)}</select><Button size="sm" variant="outline" onClick={refresh}>{ui(cs,"Refresh","Obnovit")}</Button></div>}
    {error && <p role="alert" className="rounded-xl border bg-white p-4 text-sm">{error} <Link href="/login" className="text-primary underline">{ui(cs,"Sign in","Přihlásit se")}</Link></p>}
    {!data && !error && <LoadingSkeleton />}
    {data && !filtered.length && <EmptyState title={data.length ? ui(cs,"No matching problems","Žádné odpovídající zadání") : ui(cs,"What would you like to solve?","Co chcete vyřešit?")} detail={data.length ? ui(cs,"Try a different search or status.","Zkuste jiný výraz nebo stav.") : ui(cs,"Create your first problem to start an analysis.","Vytvořte první zadání a spusťte analýzu.")}>{data.length ? <Button variant="outline" className="mt-4" onClick={() => { setSearch(""); setStatus("All"); }}>{ui(cs,"Clear filters","Vymazat filtry")}</Button> : <Button asChild className="mt-4"><Link href="/problems/new">{ui(cs,"Create a problem","Vytvořit zadání")}</Link></Button>}</EmptyState>}
    {overview && Boolean(recent.length) && <div className="grid items-stretch gap-5 xl:grid-cols-[minmax(0,1.55fr)_minmax(280px,.75fr)]">
      <section className="avenli-panel overflow-hidden rounded-[1.25rem]"><div className="flex items-center justify-between border-b px-5 py-4 sm:px-6"><div><h2 className="font-semibold tracking-[-.02em] text-[#111653]">{ui(cs,"Recent problems","Poslední zadání")}</h2><p className="mt-1 text-xs text-muted-foreground">{ui(cs,"Pick up where you left off.","Pokračujte tam, kde jste skončili.")}</p></div><Link href="/problems" className="text-sm font-semibold text-primary hover:underline">{ui(cs,"View all","Zobrazit vše")}</Link></div><div className="divide-y">{recent.map(({ problem, job, dueTaskCount }) => <Link key={problem.id} href={`/problems/${problem.id}`} className="group flex items-center gap-4 px-5 py-4 transition hover:bg-[#f8f9ff] sm:px-6"><span className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-[linear-gradient(145deg,#eef0ff,#f4edff)] text-primary"><FolderKanban className="size-[18px]" aria-hidden="true" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="truncate text-sm font-semibold text-[#151955] group-hover:text-primary">{problem.title}</h3>{dueTaskCount > 0 && <span className="rounded-full bg-amber-50 px-2 py-0.5 text-[10px] font-semibold text-amber-800">{dueTaskCount} due</span>}</div><p className="mt-1 truncate text-xs text-muted-foreground">{problem.original_input}</p></div><span className="hidden rounded-full bg-secondary px-2.5 py-1 text-[11px] font-semibold text-secondary-foreground sm:inline-flex">{uiStatus(cs,problemLabel(problem, job))}</span><ArrowRight className="size-4 shrink-0 text-muted-foreground transition group-hover:translate-x-0.5 group-hover:text-primary" aria-hidden="true" /></Link>)}</div></section>
      <aside className="avenli-glow relative flex min-h-60 flex-col overflow-hidden rounded-2xl border border-[#d9def6] p-5"><div className="absolute -right-16 -top-16 size-52 rounded-full bg-violet-300/25 blur-3xl" aria-hidden="true" /><div className="relative"><span className="flex size-9 items-center justify-center rounded-xl bg-white/80 text-primary shadow-sm"><Sparkles className="size-4" aria-hidden="true" /></span><p className="mt-4 text-[10px] font-semibold uppercase tracking-[.16em] text-[#5d5da5]">{ui(cs,"Keep going","Pokračujte")}</p><h2 className="mt-1.5 max-w-xs text-xl font-semibold leading-tight tracking-[-.04em] text-[#111653]">{ui(cs,"Turn complex problems into clear next steps.","Proměňte složité problémy v jasné další kroky.")}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{ui(cs,"Avenli researches, compares and keeps the final decision in your hands.","Avenli hledá podklady a porovnává možnosti. Konečné rozhodnutí je na vás.")}</p></div><div className="relative mt-auto flex flex-wrap gap-2 pt-4"><Button asChild size="sm"><Link href="/problems/new"><Plus aria-hidden="true" />{ui(cs,"New problem","Nové zadání")}</Link></Button><Button asChild size="sm" variant="outline"><Link href="/dashboard?demo=1">{ui(cs,"Explore demo","Prohlédnout ukázku")}</Link></Button></div></aside>
    </div>}
    {!overview && <div className="avenli-panel divide-y overflow-hidden rounded-2xl">{recent.map(({ problem, job, dueTaskCount }) => <Link key={problem.id} href={`/problems/${problem.id}`} className="group flex min-w-0 items-center gap-3 px-4 py-3.5 transition hover:bg-[#f8f9ff] sm:gap-4 sm:px-5"><span className="flex size-9 shrink-0 items-center justify-center rounded-xl bg-[#eef0ff] text-primary"><FolderKanban className="size-4" aria-hidden="true" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="truncate text-sm font-semibold text-[#151955] group-hover:text-primary">{problem.title}</h2>{dueTaskCount > 0 && <span className="rounded-full bg-amber-50 px-2 py-0.5 text-[10px] font-medium text-amber-800">{dueTaskCount} {ui(cs,"due","k termínu")}</span>}</div><p className="mt-0.5 truncate text-xs text-muted-foreground">{problem.original_input}</p></div><div className="hidden shrink-0 text-right sm:block"><p className="rounded-full bg-secondary px-2.5 py-1 text-[11px] font-semibold text-secondary-foreground">{uiStatus(cs,problemLabel(problem, job))}</p><p className="mt-1 text-[11px] text-muted-foreground">{new Date(problem.solved_at ?? problem.created_at).toLocaleDateString(cs ? "cs-CZ" : "en-US")}</p></div><ArrowRight className="size-4 shrink-0 text-muted-foreground transition group-hover:translate-x-0.5 group-hover:text-primary" aria-hidden="true" /></Link>)}</div>}
    {!overview && <Link href="/problems?demo=1" className="inline-block text-xs text-primary underline">{ui(cs,"Browse fictional examples","Prohlédnout ukázková zadání")}</Link>}
  </div>;
}
