// Generated by npm run db:types from supabase/migrations. Do not edit manually.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      agent_runs: {
        Row: {
          id: string;
          problem_id: string;
          agent_type: string;
          status: Database["public"]["Enums"]["agent_run_status"];
          input: Json;
          output: Json | null;
          model: string | null;
          tokens: number | null;
          duration_ms: number | null;
          error: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          problem_id: string;
          agent_type: string;
          status?: Database["public"]["Enums"]["agent_run_status"];
          input?: Json;
          output?: Json | null;
          model?: string | null;
          tokens?: number | null;
          duration_ms?: number | null;
          error?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          problem_id?: string;
          agent_type?: string;
          status?: Database["public"]["Enums"]["agent_run_status"];
          input?: Json;
          output?: Json | null;
          model?: string | null;
          tokens?: number | null;
          duration_ms?: number | null;
          error?: Json | null;
          created_at?: string;
        };
        Relationships: [
          { foreignKeyName: "agent_runs_problem_id_fkey"; columns: ["problem_id"]; isOneToOne: false; referencedRelation: "problems"; referencedColumns: ["id"]; },
        ];
      };
      constraints: {
        Row: {
          id: string;
          problem_id: string;
          type: string;
          description: string;
          value: Json | null;
          is_hard_constraint: boolean;
          source: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          problem_id: string;
          type: string;
          description: string;
          value?: Json | null;
          is_hard_constraint?: boolean;
          source?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          problem_id?: string;
          type?: string;
          description?: string;
          value?: Json | null;
          is_hard_constraint?: boolean;
          source?: string;
          created_at?: string;
        };
        Relationships: [
          { foreignKeyName: "constraints_problem_id_fkey"; columns: ["problem_id"]; isOneToOne: false; referencedRelation: "problems"; referencedColumns: ["id"]; },
        ];
      };
      decisions: {
        Row: {
          id: string;
          problem_id: string;
          title: string;
          decision: string;
          reasoning: string;
          confidence: Database["public"]["Enums"]["confidence_level"];
          assumptions: string[];
          created_at: string;
        };
        Insert: {
          id?: string;
          problem_id: string;
          title: string;
          decision: string;
          reasoning: string;
          confidence?: Database["public"]["Enums"]["confidence_level"];
          assumptions?: string[];
          created_at?: string;
        };
        Update: {
          id?: string;
          problem_id?: string;
          title?: string;
          decision?: string;
          reasoning?: string;
          confidence?: Database["public"]["Enums"]["confidence_level"];
          assumptions?: string[];
          created_at?: string;
        };
        Relationships: [
          { foreignKeyName: "decisions_problem_id_fkey"; columns: ["problem_id"]; isOneToOne: false; referencedRelation: "problems"; referencedColumns: ["id"]; },
        ];
      };
      full_workflow_runs: {
        Row: {
          id: string;
          problem_id: string;
          state: string;
          revision: number;
          snapshot: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          problem_id: string;
          state: string;
          revision?: number;
          snapshot: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          problem_id?: string;
          state?: string;
          revision?: number;
          snapshot?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "full_workflow_runs_problem_id_fkey"; columns: ["problem_id"]; isOneToOne: false; referencedRelation: "problems"; referencedColumns: ["id"]; },
        ];
      };
      human_requests: {
        Row: {
          run_id: string;
          problem_id: string;
          user_id: string;
          checkpoint: Json;
          questions: Json;
          response_id: string | null;
          answers: Json | null;
          created_at: string;
          answered_at: string | null;
        };
        Insert: {
          run_id: string;
          problem_id: string;
          user_id: string;
          checkpoint: Json;
          questions: Json;
          response_id?: string | null;
          answers?: Json | null;
          created_at?: string;
          answered_at?: string | null;
        };
        Update: {
          run_id?: string;
          problem_id?: string;
          user_id?: string;
          checkpoint?: Json;
          questions?: Json;
          response_id?: string | null;
          answers?: Json | null;
          created_at?: string;
          answered_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: "human_requests_problem_id_fkey"; columns: ["problem_id"]; isOneToOne: false; referencedRelation: "problems"; referencedColumns: ["id"]; },
          { foreignKeyName: "human_requests_run_id_fkey"; columns: ["run_id"]; isOneToOne: false; referencedRelation: "web_runs"; referencedColumns: ["id"]; },
        ];
      };
      monitoring_conditions: {
        Row: {
          id: string;
          user_id: string;
          problem_id: string;
          description: string;
          search_query: string;
          status: string;
          last_result: Json | null;
          last_error: string | null;
          last_checked_at: string | null;
          next_check_at: string;
          lease_until: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          problem_id: string;
          description: string;
          search_query: string;
          status?: string;
          last_result?: Json | null;
          last_error?: string | null;
          last_checked_at?: string | null;
          next_check_at?: string;
          lease_until?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          problem_id?: string;
          description?: string;
          search_query?: string;
          status?: string;
          last_result?: Json | null;
          last_error?: string | null;
          last_checked_at?: string | null;
          next_check_at?: string;
          lease_until?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "monitoring_conditions_problem_id_fkey"; columns: ["problem_id"]; isOneToOne: false; referencedRelation: "problems"; referencedColumns: ["id"]; },
        ];
      };
      notification_events: {
        Row: {
          id: string;
          user_id: string;
          problem_id: string;
          kind: string;
          event_key: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          problem_id: string;
          kind: string;
          event_key: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          problem_id?: string;
          kind?: string;
          event_key?: string;
          created_at?: string;
        };
        Relationships: [
          { foreignKeyName: "notification_events_problem_id_fkey"; columns: ["problem_id"]; isOneToOne: false; referencedRelation: "problems"; referencedColumns: ["id"]; },
        ];
      };
      notification_preferences: {
        Row: {
          user_id: string;
          analysis_updates: boolean;
          action_required: boolean;
          monitoring_updates: boolean;
        };
        Insert: {
          user_id: string;
          analysis_updates?: boolean;
          action_required?: boolean;
          monitoring_updates?: boolean;
        };
        Update: {
          user_id?: string;
          analysis_updates?: boolean;
          action_required?: boolean;
          monitoring_updates?: boolean;
        };
        Relationships: [
        ];
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          problem_id: string;
          kind: string;
          created_at: string;
          read_at: string | null;
        };
        Insert: {
          id: string;
          user_id: string;
          problem_id: string;
          kind: string;
          created_at?: string;
          read_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          problem_id?: string;
          kind?: string;
          created_at?: string;
          read_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: "notifications_id_fkey"; columns: ["id"]; isOneToOne: false; referencedRelation: "notification_events"; referencedColumns: ["id"]; },
          { foreignKeyName: "notifications_problem_id_fkey"; columns: ["problem_id"]; isOneToOne: false; referencedRelation: "problems"; referencedColumns: ["id"]; },
        ];
      };
      options: {
        Row: {
          id: string;
          problem_id: string;
          title: string;
          description: string;
          advantages: string[];
          disadvantages: string[];
          estimated_cost: number | null;
          currency: string | null;
          score: number | null;
          rejected: boolean;
          rejection_reason: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          problem_id: string;
          title: string;
          description: string;
          advantages?: string[];
          disadvantages?: string[];
          estimated_cost?: number | null;
          currency?: string | null;
          score?: number | null;
          rejected?: boolean;
          rejection_reason?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          problem_id?: string;
          title?: string;
          description?: string;
          advantages?: string[];
          disadvantages?: string[];
          estimated_cost?: number | null;
          currency?: string | null;
          score?: number | null;
          rejected?: boolean;
          rejection_reason?: string | null;
          created_at?: string;
        };
        Relationships: [
          { foreignKeyName: "options_problem_id_fkey"; columns: ["problem_id"]; isOneToOne: false; referencedRelation: "problems"; referencedColumns: ["id"]; },
        ];
      };
      plan_step_dependencies: {
        Row: {
          problem_id: string;
          plan_step_id: string;
          depends_on_id: string;
        };
        Insert: {
          problem_id: string;
          plan_step_id: string;
          depends_on_id: string;
        };
        Update: {
          problem_id?: string;
          plan_step_id?: string;
          depends_on_id?: string;
        };
        Relationships: [
          { foreignKeyName: "plan_step_dependencies_problem_id_depends_on_id_fkey"; columns: ["problem_id","depends_on_id"]; isOneToOne: false; referencedRelation: "plan_steps"; referencedColumns: ["problem_id","id"]; },
          { foreignKeyName: "plan_step_dependencies_problem_id_fkey"; columns: ["problem_id"]; isOneToOne: false; referencedRelation: "problems"; referencedColumns: ["id"]; },
          { foreignKeyName: "plan_step_dependencies_problem_id_plan_step_id_fkey"; columns: ["problem_id","plan_step_id"]; isOneToOne: false; referencedRelation: "plan_steps"; referencedColumns: ["problem_id","id"]; },
        ];
      };
      plan_steps: {
        Row: {
          id: string;
          problem_id: string;
          title: string;
          description: string | null;
          status: Database["public"]["Enums"]["step_status"];
          sequence: number;
          assigned_agent: string | null;
          created_at: string;
          completed_at: string | null;
        };
        Insert: {
          id?: string;
          problem_id: string;
          title: string;
          description?: string | null;
          status?: Database["public"]["Enums"]["step_status"];
          sequence: number;
          assigned_agent?: string | null;
          created_at?: string;
          completed_at?: string | null;
        };
        Update: {
          id?: string;
          problem_id?: string;
          title?: string;
          description?: string | null;
          status?: Database["public"]["Enums"]["step_status"];
          sequence?: number;
          assigned_agent?: string | null;
          created_at?: string;
          completed_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: "plan_steps_problem_id_fkey"; columns: ["problem_id"]; isOneToOne: false; referencedRelation: "problems"; referencedColumns: ["id"]; },
        ];
      };
      problems: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          original_input: string;
          status: Database["public"]["Enums"]["problem_status"];
          goal: string | null;
          summary: string | null;
          progress: number;
          confidence: Database["public"]["Enums"]["confidence_level"] | null;
          current_priority: string | null;
          created_at: string;
          updated_at: string;
          solved_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          original_input: string;
          status?: Database["public"]["Enums"]["problem_status"];
          goal?: string | null;
          summary?: string | null;
          progress?: number;
          confidence?: Database["public"]["Enums"]["confidence_level"] | null;
          current_priority?: string | null;
          created_at?: string;
          updated_at?: string;
          solved_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          original_input?: string;
          status?: Database["public"]["Enums"]["problem_status"];
          goal?: string | null;
          summary?: string | null;
          progress?: number;
          confidence?: Database["public"]["Enums"]["confidence_level"] | null;
          current_priority?: string | null;
          created_at?: string;
          updated_at?: string;
          solved_at?: string | null;
        };
        Relationships: [
        ];
      };
      profiles: {
        Row: {
          id: string;
          display_name: string | null;
          avatar_url: string | null;
          timezone: string;
          preferred_language: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          display_name?: string | null;
          avatar_url?: string | null;
          timezone?: string;
          preferred_language?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          display_name?: string | null;
          avatar_url?: string | null;
          timezone?: string;
          preferred_language?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
        ];
      };
      research_items: {
        Row: {
          id: string;
          problem_id: string;
          plan_step_id: string | null;
          title: string;
          claim: string;
          summary: string | null;
          source_url: string;
          source_name: string;
          source_date: string | null;
          confidence: Database["public"]["Enums"]["confidence_level"];
          verified: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          problem_id: string;
          plan_step_id?: string | null;
          title: string;
          claim: string;
          summary?: string | null;
          source_url: string;
          source_name: string;
          source_date?: string | null;
          confidence?: Database["public"]["Enums"]["confidence_level"];
          verified?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          problem_id?: string;
          plan_step_id?: string | null;
          title?: string;
          claim?: string;
          summary?: string | null;
          source_url?: string;
          source_name?: string;
          source_date?: string | null;
          confidence?: Database["public"]["Enums"]["confidence_level"];
          verified?: boolean;
          created_at?: string;
        };
        Relationships: [
          { foreignKeyName: "research_items_problem_id_fkey"; columns: ["problem_id"]; isOneToOne: false; referencedRelation: "problems"; referencedColumns: ["id"]; },
          { foreignKeyName: "research_items_problem_id_plan_step_id_fkey"; columns: ["problem_id","plan_step_id"]; isOneToOne: false; referencedRelation: "plan_steps"; referencedColumns: ["problem_id","id"]; },
        ];
      };
      risks: {
        Row: {
          id: string;
          problem_id: string;
          title: string;
          description: string;
          severity: Database["public"]["Enums"]["priority_level"];
          probability: number | null;
          mitigation: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          problem_id: string;
          title: string;
          description: string;
          severity?: Database["public"]["Enums"]["priority_level"];
          probability?: number | null;
          mitigation?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          problem_id?: string;
          title?: string;
          description?: string;
          severity?: Database["public"]["Enums"]["priority_level"];
          probability?: number | null;
          mitigation?: string | null;
          created_at?: string;
        };
        Relationships: [
          { foreignKeyName: "risks_problem_id_fkey"; columns: ["problem_id"]; isOneToOne: false; referencedRelation: "problems"; referencedColumns: ["id"]; },
        ];
      };
      tasks: {
        Row: {
          id: string;
          problem_id: string;
          title: string;
          description: string | null;
          status: Database["public"]["Enums"]["task_status"];
          priority: Database["public"]["Enums"]["priority_level"];
          due_at: string | null;
          created_at: string;
          completed_at: string | null;
        };
        Insert: {
          id?: string;
          problem_id: string;
          title: string;
          description?: string | null;
          status?: Database["public"]["Enums"]["task_status"];
          priority?: Database["public"]["Enums"]["priority_level"];
          due_at?: string | null;
          created_at?: string;
          completed_at?: string | null;
        };
        Update: {
          id?: string;
          problem_id?: string;
          title?: string;
          description?: string | null;
          status?: Database["public"]["Enums"]["task_status"];
          priority?: Database["public"]["Enums"]["priority_level"];
          due_at?: string | null;
          created_at?: string;
          completed_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: "tasks_problem_id_fkey"; columns: ["problem_id"]; isOneToOne: false; referencedRelation: "problems"; referencedColumns: ["id"]; },
        ];
      };
      unknowns: {
        Row: {
          id: string;
          problem_id: string;
          description: string;
          importance: Database["public"]["Enums"]["priority_level"];
          status: Database["public"]["Enums"]["unknown_status"];
          resolution: string | null;
          confidence: Database["public"]["Enums"]["confidence_level"] | null;
          created_at: string;
          resolved_at: string | null;
        };
        Insert: {
          id?: string;
          problem_id: string;
          description: string;
          importance?: Database["public"]["Enums"]["priority_level"];
          status?: Database["public"]["Enums"]["unknown_status"];
          resolution?: string | null;
          confidence?: Database["public"]["Enums"]["confidence_level"] | null;
          created_at?: string;
          resolved_at?: string | null;
        };
        Update: {
          id?: string;
          problem_id?: string;
          description?: string;
          importance?: Database["public"]["Enums"]["priority_level"];
          status?: Database["public"]["Enums"]["unknown_status"];
          resolution?: string | null;
          confidence?: Database["public"]["Enums"]["confidence_level"] | null;
          created_at?: string;
          resolved_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: "unknowns_problem_id_fkey"; columns: ["problem_id"]; isOneToOne: false; referencedRelation: "problems"; referencedColumns: ["id"]; },
        ];
      };
      web_runs: {
        Row: {
          id: string;
          user_id: string;
          problem_id: string | null;
          status: string;
          secret_token: string;
          error: string | null;
          created_at: string;
          expires_at: string;
          recovery_count: number;
          last_heartbeat_at: string | null;
        };
        Insert: {
          id: string;
          user_id: string;
          problem_id?: string | null;
          status: string;
          secret_token: string;
          error?: string | null;
          created_at?: string;
          expires_at?: string;
          recovery_count?: number;
          last_heartbeat_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          problem_id?: string | null;
          status?: string;
          secret_token?: string;
          error?: string | null;
          created_at?: string;
          expires_at?: string;
          recovery_count?: number;
          last_heartbeat_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: "web_runs_problem_id_fkey"; columns: ["problem_id"]; isOneToOne: false; referencedRelation: "problems"; referencedColumns: ["id"]; },
        ];
      };
      workflow_runs: {
        Row: {
          id: string;
          problem_id: string;
          state: string;
          revision: number;
          snapshot: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          problem_id: string;
          state: string;
          revision?: number;
          snapshot: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          problem_id?: string;
          state?: string;
          revision?: number;
          snapshot?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "workflow_runs_problem_id_fkey"; columns: ["problem_id"]; isOneToOne: false; referencedRelation: "problems"; referencedColumns: ["id"]; },
        ];
      };
    };
    Views: { [_ in never]: never };
    Functions: {
      claim_web_run: { Args: {
        p_run_id: string | null;
        p_secret: string | null;
      }; Returns: Json; };
      create_monitoring_condition: { Args: {
        p_problem_id: string | null;
        p_description: string | null;
        p_search_query: string | null;
      }; Returns: Json; };
      finish_web_run: { Args: {
        p_run_id: string | null;
        p_secret: string | null;
        p_status: string | null;
        p_error?: string | null;
      }; Returns: boolean; };
      pause_web_run: { Args: {
        p_run_id: string | null;
        p_secret: string | null;
        p_checkpoint: Json | null;
      }; Returns: boolean; };
      read_notification: { Args: {
        p_id: string | null;
      }; Returns: boolean; };
      recover_web_run: { Args: {
        p_run_id: string | null;
        p_secret: string | null;
      }; Returns: Json; };
      reserve_web_run: { Args: {
        p_request_id: string | null;
        p_secret: string | null;
        p_problem_id?: string | null;
        p_description?: string | null;
      }; Returns: Json; };
      respond_web_run: { Args: {
        p_run_id: string | null;
        p_problem_id: string | null;
        p_secret: string | null;
        p_response_id: string | null;
        p_answers: Json | null;
      }; Returns: Json; };
      save_notification_preferences: { Args: {
        p_analysis: boolean | null;
        p_action: boolean | null;
        p_monitoring: boolean | null;
      }; Returns: undefined; };
      set_monitoring_condition_status: { Args: {
        p_condition_id: string | null;
        p_status: string | null;
      }; Returns: Json; };
      yield_web_run: { Args: {
        p_run_id: string | null;
        p_secret: string | null;
      }; Returns: boolean; };
    };
    Enums: {
      agent_run_status: "pending" | "running" | "completed" | "failed";
      confidence_level: "low" | "medium" | "high";
      priority_level: "low" | "medium" | "high" | "critical";
      problem_status: "analyzing" | "planning" | "researching" | "verifying" | "evaluating" | "action_required" | "waiting" | "monitoring" | "solved" | "failed";
      step_status: "pending" | "running" | "completed" | "failed" | "skipped";
      task_status: "pending" | "in_progress" | "completed" | "cancelled";
      unknown_status: "unresolved" | "researching" | "needs_user" | "resolved";
    };
    CompositeTypes: { [_ in never]: never };
  };
};
