"use client";
import { ArrowRight, CheckCircle2, ListChecks, Search, ShieldCheck, Sparkles } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { AvenliMark } from "@/components/brand";
import { BrandLandscape } from "@/components/brand-landscape";
import { usePublicCzech } from "@/components/public-language";

export default function HomePage() {
  const cs = usePublicCzech();
  const t = (en: string, cz: string) => cs ? cz : en;
  const steps = [
    { icon: Search, en: "Understand the problem", cs: "Porozumět zadání" },
    { icon: Search, en: "Research with sources", cs: "Prozkoumat zdroje" },
    { icon: ListChecks, en: "Compare approaches", cs: "Porovnat možnosti" },
    { icon: ShieldCheck, en: "Recommend next steps", cs: "Navrhnout další kroky" },
  ];
  return <div className="overflow-hidden">
    <section className="relative isolate mx-auto grid min-h-[620px] max-w-7xl items-center gap-12 overflow-hidden px-5 py-16 sm:px-8 lg:grid-cols-[1.05fr_.95fr] lg:py-20">
      <div className="absolute -left-40 top-16 -z-10 size-96 rounded-full bg-violet-200/40 blur-3xl" aria-hidden="true"/><div className="absolute -right-32 top-0 -z-10 size-[30rem] rounded-full bg-blue-200/35 blur-3xl" aria-hidden="true"/>
      <BrandLandscape className="absolute bottom-0 right-[-12%] -z-10 h-[22rem] w-[80%] opacity-35 max-lg:w-full max-lg:opacity-20" />
      <div className="avenli-hero-copy max-w-2xl"><p className="inline-flex items-center gap-2 rounded-full border border-[#dddef9] bg-white/80 px-4 py-2 text-xs font-semibold uppercase tracking-[.16em] text-[#4c47b5]"><Sparkles className="size-4" aria-hidden="true"/>{t("A workspace for decisions", "Prostor pro rozhodování")}</p><h1 className="mt-7 text-5xl font-semibold leading-[1.04] tracking-[-.055em] text-[#0f1554] sm:text-7xl">{t("Give it a problem.", "Svěřte nám problém.")}<br/><span className="bg-[linear-gradient(90deg,#3e50ee,#8738ef)] bg-clip-text text-transparent">{t("Get it solved.", "Získejte jasný postup.")}</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-[#5e6582] sm:text-xl">{t("Avenli keeps research, options, uncertainty and next steps in one saved workspace.", "Avenli spojuje výzkum, možnosti, nejistoty a další kroky do jednoho uloženého prostoru.")}</p><div className="mt-9 flex flex-wrap gap-3"><Button asChild size="lg" className="rounded-xl bg-[linear-gradient(135deg,#3c52ef,#8138f2)] px-7 shadow-xl shadow-violet-200"><Link href="/register">{t("Get started", "Začít")} <ArrowRight aria-hidden="true"/></Link></Button><Button asChild size="lg" variant="outline" className="rounded-xl border-[#d8daf0] bg-white/80 px-7"><Link href="/demo">{t("Explore the demo", "Prohlédnout ukázku")}</Link></Button></div><p className="mt-5 text-sm text-muted-foreground">{t("You review every recommendation. External actions need separate approval.", "Každé doporučení posuzujete vy. Vnější akce vyžadují zvláštní schválení.")}</p></div>
      <div className="avenli-hero-preview relative mx-auto w-full max-w-lg"><div className="absolute -inset-8 rounded-[3rem] bg-[linear-gradient(135deg,rgba(79,75,246,.18),rgba(59,183,255,.14))] blur-2xl" aria-hidden="true"/><div className="relative rounded-[2rem] border border-white/80 bg-white/90 p-5 shadow-[0_30px_80px_rgba(32,35,104,.18)] backdrop-blur"><div className="flex items-center gap-3 border-b pb-5"><span className="flex size-12 items-center justify-center rounded-2xl bg-[#f1f0ff]"><AvenliMark/></span><div><p className="font-semibold text-[#15195a]">{t("Avenli is working on it", "Avenli na tom pracuje")}</p><p className="text-sm text-muted-foreground">{t("Saved steps you can return to", "Uložené kroky, ke kterým se vrátíte")}</p></div></div><ol className="mt-6 space-y-4">{steps.map(({icon:Icon,en,cs:cz}, index)=><li key={en} className="flex items-center gap-4"><span className={`flex size-9 items-center justify-center rounded-full ${index < 2 ? "bg-emerald-50 text-emerald-600" : "bg-[#f0f1fb] text-[#777d9b]"}`}>{index < 2 ? <CheckCircle2 className="size-5"/> : <Icon className="size-4"/>}</span><p className="text-sm font-medium">{t(en,cz)}</p></li>)}</ol><div className="mt-7 rounded-2xl bg-[linear-gradient(135deg,#121957,#292169)] p-5 text-white"><p className="text-xs uppercase tracking-[.15em] text-indigo-200">{t("A clear next step", "Jasný další krok")}</p><p className="mt-2 text-lg font-medium">{t("See what is known, what is missing and what to do next.", "Uvidíte, co víme, co chybí a co udělat dál.")}</p></div></div></div>
    </section>
    <section className="border-y border-[#e5e7f3] bg-white/80"><div className="mx-auto max-w-7xl px-5 py-14 sm:px-8"><p className="text-xs font-semibold uppercase tracking-[.16em] text-primary">{t("Why Avenli?", "Proč Avenli?")}</p><h2 className="mt-2 max-w-3xl text-3xl font-semibold tracking-tight">{t("Built for a decision that outlives one chat", "Pro rozhodnutí, které nekončí jedním chatem")}</h2><p className="mt-4 max-w-3xl text-sm leading-7 text-muted-foreground">{t("General AI assistants are great for conversation. Avenli focuses on a saved problem-solving workflow: it separates evidence from assumptions, asks when essential information is missing, compares options, and turns the result into reviewable tasks.", "Běžní AI asistenti se hodí pro konverzaci. Avenli se zaměřuje na uložený postup řešení: odděluje zdroje od předpokladů, ptá se na chybějící informace, porovnává možnosti a převádí výsledek na úkoly k posouzení.")}</p><div className="mt-8 grid gap-4 md:grid-cols-3">{[
      [t("Traceable sources", "Dohledatelné zdroje"),t("Open source links and check how strongly they support each claim.","Otevřete zdroje a zjistěte, nakolik podporují jednotlivá tvrzení.")],
      [t("Honest uncertainty", "Přiznaná nejistota"),t("Unanswered questions and weak evidence remain visible.","Nezodpovězené otázky a slabé důkazy zůstávají viditelné.")],
      [t("Action on your terms", "Akce pod vaší kontrolou"),t("Proposed tasks are saved; external changes require explicit review.","Navržené úkoly se ukládají; vnější změny vyžadují výslovné schválení.")],
    ].map(([title,body])=><article key={title} className="avenli-benefit-card rounded-2xl border bg-white p-5"><h3 className="font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{body}</p></article>)}</div><p className="mt-6 text-xs text-muted-foreground">{t("Avenli is a focused workflow, not a claim that every answer is more accurate than ChatGPT or Gemini. Always review important decisions.","Avenli nabízí soustředěný postup, nikoli slib, že každá odpověď bude přesnější než ChatGPT nebo Gemini. Důležitá rozhodnutí si vždy ověřte.")}</p></div></section>
  </div>;
}
